all: exec

main.o: main.c fonctions.h
				gcc -c main.c -o main.o

fonctions.o: fonctions.c fonctions.h
				gcc -c fonctions.c -o fonctions.o

exec: fonctions.o main.o
				gcc fonctions.o main.o -o exec